import login from "../services/ecount/login.js";
import saveSales from "../services/ecount/saveSales.js";

export default async function createEcountSale(inputValue) {
    try {
        const SESSION_ID = await login();
        if (!SESSION_ID) throw new Error('SESSION_ID 為空');
        await saveSales(SESSION_ID,inputValue);
    } catch (error) {
        console.log(`執行失敗`)
        console.error(error.message)
    }
}

// 示範資料
// const inputValue = {
    //   "SaleList": [{
    //     "BulkDatas": {
    //       "IO_DATE": orderDateStr,
    //       "UPLOAD_SER_NO": order.name || order.id,
    //       "CUST": "",
    //       "CUST_DES": "",
    //       "EMP_CD": "",
    //       "WH_CD": "00009",
    //       "IO_TYPE": "",
    //       "EXCHANGE_TYPE": "",
    //       "EXCHANGE_RATE": "",
    //       "SITE": "",
    //       "PJT_CD": "",
    //       "DOC_NO": "",
    //       "TTL_CTT": "",
    //       "U_MEMO1": orderDateStr,
    //       "U_MEMO2": "",
    //       "U_MEMO3": "",
    //       "U_MEMO4": "",
    //       "U_MEMO5": "",
    //       "ADD_TXT_01_T": "",
    //       "ADD_TXT_02_T": "",
    //       "ADD_TXT_03_T": "",
    //       "ADD_TXT_04_T": "",
    //       "ADD_TXT_05_T": "",
    //       "ADD_TXT_06_T": "",
    //       "ADD_TXT_07_T": "",
    //       "ADD_TXT_08_T": "",
    //       "ADD_TXT_09_T": "",
    //       "ADD_TXT_10_T": "",
    //       "ADD_NUM_01_T": "",
    //       "ADD_NUM_02_T": "",
    //       "ADD_NUM_03_T": "",
    //       "ADD_NUM_04_T": "",
    //       "ADD_NUM_05_T": "",
    //       "ADD_CD_01_T": "",
    //       "ADD_CD_02_T": "",
    //       "ADD_CD_03_T": "",
    //       "ADD_DATE_01_T": "",
    //       "ADD_DATE_02_T": "",
    //       "ADD_DATE_03_T": "",
    //       "U_TXT1": "",
    //       "ADD_LTXT_01_T": "",
    //       "ADD_LTXT_02_T": "",
    //       "ADD_LTXT_03_T": "",
    //       "PROD_CD": "M1DXRBLCULCU2OZH10M",
    //       "PROD_DES": "test",
    //       "SIZE_DES": "",
    //       "UQTY": "",
    //       "QTY": "1",
    //       "PRICE": "",
    //       "USER_PRICE_VAT": "",
    //       "SUPPLY_AMT": "",
    //       "SUPPLY_AMT_F": "",
    //       "VAT_AMT": "",
    //       "REMARKS": "",
    //       "ITEM_CD": "",
    //       "P_REMARKS1": "",
    //       "P_REMARKS2": "",
    //       "P_REMARKS3": "",
    //       "ADD_TXT_01": "",
    //       "ADD_TXT_02": "",
    //       "ADD_TXT_03": "",
    //       "ADD_TXT_04": "",
    //       "ADD_TXT_05": "",
    //       "ADD_TXT_06": "",
    //       "REL_DATE": orderDateStr,
    //       "REL_NO": "",
    //       "MAKE_FLAG": "",
    //       "CUST_AMT": "",
    //       "P_AMT1": "",
    //       "P_AMT2": "",
    //       "ADD_NUM_01": "",
    //       "ADD_NUM_02": "",
    //       "ADD_NUM_03": "",
    //       "ADD_CD_01": "",
    //       "ADD_CD_02": "",
    //       "ADD_CD_03": "",
    //       "ADD_CD_NM_01": "",
    //       "ADD_CD_NM_02": "",
    //       "ADD_CD_NM_03": "",
    //       "ADD_CDNM_01": "",
    //       "ADD_CDNM_02": "",
    //       "ADD_CDNM_03": "",
    //       "ADD_DATE_01": "",
    //       "ADD_DATE_02": "",
    //       "ADD_DATE_03": ""
    //     }
    //   }]
    // }

    // 串過的資料
    // {
    //     "BulkDatas": {
    //       "IO_DATE": ex.createdDate8,
    //       "UPLOAD_SER_NO": String(ex.number ?? ex.id),
    //       "CUST": "10015",
    //       "CUST_DES": "Shopify",
    //       "EMP_CD": "10007",
    //       "WH_CD": ex.singleWarehouseId === 81795907814 ? "100" : "200", //如果是深圳倉庫 200 台灣倉庫 100
    //       "IO_TYPE": "",
    //       "EXCHANGE_TYPE": "00002",
    //       "EXCHANGE_RATE": "",
    //       "SITE": "",
    //       "PJT_CD": "",
    //       "DOC_NO": "",
    //       "TTL_CTT": "",
    //       "U_MEMO1": ex.createdDate8,
    //       "U_MEMO2": ex.title,
    //       "U_MEMO3": "",
    //       "U_MEMO4": "",
    //       "U_MEMO5": "",
    //       "ADD_TXT_01_T": "",
    //       "ADD_TXT_02_T": "",
    //       "ADD_TXT_03_T": "",
    //       "ADD_TXT_04_T": "",
    //       "ADD_TXT_05_T": "",
    //       "ADD_TXT_06_T": "",
    //       "ADD_TXT_07_T": "",
    //       "ADD_TXT_08_T": "",
    //       "ADD_TXT_09_T": "",
    //       "ADD_TXT_10_T": "",
    //       "ADD_NUM_01_T": "",
    //       "ADD_NUM_02_T": "",
    //       "ADD_NUM_03_T": "",
    //       "ADD_NUM_04_T": "",
    //       "ADD_NUM_05_T": "",
    //       "ADD_CD_01_T": "",
    //       "ADD_CD_02_T": "",
    //       "ADD_CD_03_T": "",
    //       "ADD_DATE_01_T": "",
    //       "ADD_DATE_02_T": "",
    //       "ADD_DATE_03_T": "",
    //       "U_TXT1": "",
    //       "ADD_LTXT_01_T": ex.shippingAddress,
    //       "ADD_LTXT_02_T": "",
    //       "ADD_LTXT_03_T": "",
    //       "PROD_CD": "M1DX5001RZH-010M", //要先以SKU查詢品項編碼，多產品要發兩次，序號一致就會綁定在一起(推測)
    //       "PROD_DES": "",
    //       "SIZE_DES": "",
    //       "UQTY": "",
    //       "QTY": item.quantity,
    //       "PRICE": ex.singleWarehouseId === 81795907814 ? "" : item.price, //單價(美國訂單)
    //       "USER_PRICE_VAT": ex.singleWarehouseId === 81795907814 ? item.price : "", //單價含稅(台灣訂單)
    //       "SUPPLY_AMT": "",
    //       "SUPPLY_AMT_F": "",
    //       "VAT_AMT": "",
    //       "REMARKS": "",
    //       "ITEM_CD": "",
    //       "P_REMARKS1": "",
    //       "P_REMARKS2": "",
    //       "P_REMARKS3": "",
    //       "ADD_TXT_01": "",
    //       "ADD_TXT_02": "",
    //       "ADD_TXT_03": "",
    //       "ADD_TXT_04": "",
    //       "ADD_TXT_05": "",
    //       "ADD_TXT_06": "",
    //       "REL_DATE": ex.createdDate8,
    //       "REL_NO": "",
    //       "MAKE_FLAG": "",
    //       "CUST_AMT": "",
    //       "P_AMT1": "",
    //       "P_AMT2": "",
    //       "ADD_NUM_01": "",
    //       "ADD_NUM_02": "",
    //       "ADD_NUM_03": "",
    //       "ADD_CD_01": "",
    //       "ADD_CD_02": "",
    //       "ADD_CD_03": "",
    //       "ADD_CD_NM_01": "",
    //       "ADD_CD_NM_02": "",
    //       "ADD_CD_NM_03": "",
    //       "ADD_CDNM_01": "",
    //       "ADD_CDNM_02": "",
    //       "ADD_CDNM_03": "",
    //       "ADD_DATE_01": "",
    //       "ADD_DATE_02": "",
    //       "ADD_DATE_03": ""
    //     }
    //   }