import formatDateYYYYMMDD from "./formatDateYYYYMMDD.js";

export default function buildSales_amazon(newSalesProducts) {
    const date = formatDateYYYYMMDD(new Date());

    const SaleList = [];

    for (const item of newSalesProducts) {
        SaleList.push({
        "BulkDatas": {
          "IO_DATE": date[1],
          "UPLOAD_SER_NO": date[1].slice(-4),
          "CUST": "10018",
          "CUST_DES": "",
          "EMP_CD": "10019",
          "WH_CD": "300",
          "IO_TYPE": "",
          "EXCHANGE_TYPE": "",
          "EXCHANGE_RATE": "",
          "SITE": "",
          "PJT_CD": "",
          "DOC_NO": "",
          "TTL_CTT": "",
          "U_MEMO1": date[1],
          "U_MEMO2": "",
          "U_MEMO3": "",
          "U_MEMO4": "",
          "U_MEMO5": "",
          "ADD_TXT_01_T": "",
          "ADD_TXT_02_T": "",
          "ADD_TXT_03_T": "",
          "ADD_TXT_04_T": "",
          "ADD_TXT_05_T": "",
          "ADD_TXT_06_T": "",
          "ADD_TXT_07_T": "",
          "ADD_TXT_08_T": "",
          "ADD_TXT_09_T": "",
          "ADD_TXT_10_T": "",
          "ADD_NUM_01_T": "",
          "ADD_NUM_02_T": "",
          "ADD_NUM_03_T": "",
          "ADD_NUM_04_T": "",
          "ADD_NUM_05_T": "",
          "ADD_CD_01_T": "",
          "ADD_CD_02_T": "",
          "ADD_CD_03_T": "",
          "ADD_DATE_01_T": "",
          "ADD_DATE_02_T": "",
          "ADD_DATE_03_T": "",
          "U_TXT1": "",
          "ADD_LTXT_01_T": "",
          "ADD_LTXT_02_T": "",
          "ADD_LTXT_03_T": "",
          "PROD_CD": item.fnSku,
          "PROD_DES": "",
          "SIZE_DES": "",
          "UQTY": "",
          "QTY": item.deltaQty,
          "PRICE": "",
          "USER_PRICE_VAT": "",
          "SUPPLY_AMT": "",
          "SUPPLY_AMT_F": "",
          "VAT_AMT": "",
          "REMARKS": "",
          "ITEM_CD": "",
          "P_REMARKS1": "",
          "P_REMARKS2": "",
          "P_REMARKS3": "",
          "ADD_TXT_01": "",
          "ADD_TXT_02": "",
          "ADD_TXT_03": "",
          "ADD_TXT_04": "",
          "ADD_TXT_05": "",
          "ADD_TXT_06": "",
          "REL_DATE": date[1],
          "REL_NO": "",
          "MAKE_FLAG": "",
          "CUST_AMT": "",
          "P_AMT1": "",
          "P_AMT2": "",
          "ADD_NUM_01": "",
          "ADD_NUM_02": "",
          "ADD_NUM_03": "",
          "ADD_CD_01": "",
          "ADD_CD_02": "",
          "ADD_CD_03": "",
          "ADD_CD_NM_01": "",
          "ADD_CD_NM_02": "",
          "ADD_CD_NM_03": "",
          "ADD_CDNM_01": "",
          "ADD_CDNM_02": "",
          "ADD_CDNM_03": "",
          "ADD_DATE_01": "",
          "ADD_DATE_02": "",
          "ADD_DATE_03": ""
        }
      });
    }

    return SaleList
}