export default function buildBasicProduct_amazon(newProducts) {
    
    const productList = [];

    for (const item of newProducts) {
        productList.push({
            "BulkDatas": {
                "PROD_CD": item.fnSku,
                "PROD_DES": item.asin,       
                "SIZE_FLAG": "",
                "SIZE_DES": item.sellerSku,
                "UNIT": "psc",
                "PROD_TYPE": "",
                "SET_FLAG": "",
                "BAL_FLAG": "",
                "WH_CD": "",
                "IN_PRICE": "",
                "IN_PRICE_VAT": "",
                "OUT_PRICE": "",
                "OUT_PRICE_VAT": "",
                "REMARKS_WIN": "",
                "CLASS_CD": "",
                "CLASS_CD2": "",
                "CLASS_CD3": "",
                "BAR_CODE": item.fnSku,
                "VAT_YN": "",
                "TAX": "",
                "VAT_RATE_BY_BASE_YN": "",
                "VAT_RATE_BY": "",
                "CS_FLAG": "",
                "REMARKS": `FBA Inventory：${item.productName}`,      // keep long title here
                "INSPECT_TYPE_CD": "",
                "INSPECT_STATUS": "",
                "SAMPLE_PERCENT": "",
                "EXCH_RATE": "",
                "DENO_RATE": "",
                "SAFE_A0001": "",
                "SAFE_A0002": "",
                "SAFE_A0003": "",
                "SAFE_A0004": "",
                "SAFE_A0005": "",
                "SAFE_A0006": "",
                "SAFE_A0007": "",
                "CSORD_C0001": "",
                "CSORD_TEXT": "",
                "CSORD_C0003": "",
                "IN_TERM": "",
                "MIN_QTY": "",
                "CUST": "",
                "OUT_PRICE1": "",
                "OUT_PRICE1_VAT_YN": "",
                "OUT_PRICE2": "",
                "OUT_PRICE2_VAT_YN": "",
                "OUT_PRICE3": "",
                "OUT_PRICE3_VAT_YN": "",
                "OUT_PRICE4": "",
                "OUT_PRICE4_VAT_YN": "",
                "OUT_PRICE5": "",
                "OUT_PRICE5_VAT_YN": "",
                "OUT_PRICE6": "",
                "OUT_PRICE6_VAT_YN": "",
                "OUT_PRICE7": "",
                "OUT_PRICE7_VAT_YN": "",
                "OUT_PRICE8": "",
                "OUT_PRICE8_VAT_YN": "",
                "OUT_PRICE9": "",
                "OUT_PRICE9_VAT_YN": "",
                "OUT_PRICE10": "",
                "OUT_PRICE10_VAT_YN": "",
                "OUTSIDE_PRICE": "",
                "OUTSIDE_PRICE_VAT": "",
                "LABOR_WEIGHT": "",
                "EXPENSES_WEIGHT": "",
                "MATERIAL_COST": "",
                "EXPENSE_COST": "",
                "LABOR_COST": "",
                "OUT_COST": "",
                "CONT1": "",
                "CONT2": "",
                "CONT3": "",
                "CONT4": "",
                "CONT5": "",
                "CONT6": "",
                "NO_USER1": "",
                "NO_USER2": "",
                "NO_USER3": "",
                "NO_USER4": "",
                "NO_USER5": "",
                "NO_USER6": "",
                "NO_USER7": "",
                "NO_USER8": "",
                "NO_USER9": "",
                "NO_USER10": "",
                "ITEM_TYPE": "",
                "SERIAL_TYPE": "",
                "PROD_SELL_TYPE": "",
                "PROD_WHMOVE_TYPE": "",
                "QC_BUY_TYPE": "",
                "QC_YN": ""
            }
        });
    }

    return productList
}