
export const metafieldTypes = {
  //Filter
  "filter.transceiverType": "list.single_line_text_field",
  "filter.fiberMode": "list.single_line_text_field",
  "filter.connectorType": "list.single_line_text_field",
  "filter.polishType": "list.single_line_text_field",
  "filter.transmissionMode": "list.single_line_text_field",
  "filter.insertionLossGrade": "list.single_line_text_field",
  "filter.transmissionDistance": "list.single_line_text_field",
  "filter.data_rate_gbps": "list.single_line_text_field",
  "filter.branchType": "list.single_line_text_field",
  "filter.fiberCount": "list.single_line_text_field",
  "filter.connectorGender": "list.single_line_text_field",
  "filter.connectorColor": "list.single_line_text_field",
  "filter.jacketColor": "list.single_line_text_field",
  "filter.jacket": "list.single_line_text_field",
  "filter.wavelength_filter": "list.single_line_text_field",
  "filter.polarity": "list.single_line_text_field",
  "filter.bodyType": "list.single_line_text_field",
  "filter.gender": "list.single_line_text_field",
  "filter.connector_a": "list.single_line_text_field",
  "filter.connector_b": "list.single_line_text_field",
  "filter.weight": "number_integer",
  //Theme
  "theme.label_1": "list.single_line_text_field",
  "theme.label_2": "list.single_line_text_field",
  "theme.label_3": "list.single_line_text_field",
  "theme.label_4": "list.single_line_text_field",
  "theme.label_1_bg_color": "color",
  "theme.label_1_text_color": "color",
  "theme.label_2_bg_color": "color",
  "theme.label_2_text_color": "color",
  "theme.label_3_bg_color": "color",
  "theme.label_3_text_color": "color",
  "theme.label_4_bg_color": "color",
  "theme.label_4_text_color": "color",
  "theme.highlight": "boolean",
  "theme.inquiry": "boolean",
  "theme.shipping_time": "multi_line_text_field",
  //Table
  "table.CiscoCompatible": "multi_line_text_field",
  "table.VendorName": "multi_line_text_field",
  "table.form_factor": "multi_line_text_field",
  "table.max_data_rate": "multi_line_text_field",
  "table.wavelength": "multi_line_text_field",
  "table.max_cable_distance": "multi_line_text_field",
  "table.connector": "multi_line_text_field",
  "table.media": "multi_line_text_field",
  "table.transmitter_type": "multi_line_text_field",
  "table.receiver_type": "multi_line_text_field",
  "table.tx_power": "multi_line_text_field",
  "table.minimum_receiver_power": "multi_line_text_field",
  "table.power_budget": "multi_line_text_field",
  "table.receiver_overload": "multi_line_text_field",
  "table.typical_power_consumption": "multi_line_text_field",
  "table.extinction_ratio": "multi_line_text_field",
  "table.ddm_dom": "multi_line_text_field",
  "table.commercial_temperature_range": "multi_line_text_field",
  "table.cdr_clock_and_data_recovery": "multi_line_text_field",
  "table.inbuilt_fec": "multi_line_text_field",
  "table.protocols": "multi_line_text_field",
  "table.warranty": "multi_line_text_field",
  "table.storage_temperature": "multi_line_text_field",
  "table.operating_temperature": "multi_line_text_field",
  "table.cable_outside_diameter_od": "multi_line_text_field",
  "table.fiber_count": "multi_line_text_field",
  "table.return_loss": "multi_line_text_field",
  "table.insertion_loss": "multi_line_text_field",
  "table.attenuation_at_1300nm": "multi_line_text_field",
  "table.attenuation_at_850nm": "multi_line_text_field",
  "table.fiber_mode": "multi_line_text_field",
  "table.polarity": "multi_line_text_field",
  "table.polish_type": "multi_line_text_field",
  "tableconnector_b": "multi_line_text_field",
  "tableconnector_a": "multi_line_text_field",
  "table.mtp_connector_il": "multi_line_text_field",
  "table.mtp_connector_rl": "multi_line_text_field",
  "table.mpo_connector_il": "multi_line_text_field",
  "table.mpo_connector_rl": "multi_line_text_field",
  "table.lc_connector_il": "multi_line_text_field",
  "table.lc_connector_rl": "multi_line_text_field",
  "table.attenuation_at_1310nm": "multi_line_text_field",
  "table.attenuation_at_1550nm": "multi_line_text_field",
  "table.breakout_outside_diameter_od": "multi_line_text_field",
  "table.part_number": "multi_line_text_field",
  "table.optical_components": "multi_line_text_field",
  "table.dom_support": "multi_line_text_field",
  "table.receiver_sensitivity": "multi_line_text_field",
  "table.industrial_temperature_range": "multi_line_text_field",
  "table.rx_los": "multi_line_text_field",
  "table.connector_a": "multi_line_text_field",
  "table.connector_b": "multi_line_text_field",
  "table.bit_error_ratio_ber": "multi_line_text_field",
  "table.emc": "multi_line_text_field",
  "table.mtbf_sx": "multi_line_text_field",
  "table.modulation": "multi_line_text_field",
  "table.application_field": "multi_line_text_field",
  "table.core_size": "multi_line_text_field",
  "table.dimension_hxwxd": "multi_line_text_field",
  "table.PackagingTechnology": "multi_line_text_field",
  "table.operating_temperature_range": "multi_line_text_field",
  "table.cable_type": "multi_line_text_field",
  "table.modulation_electrical": "multi_line_text_field",
  "table.modulation_optical": "multi_line_text_field",
  "table.connector_color": "multi_line_text_field",
  "table.jacket_color": "multi_line_text_field",
  "table.cable_dia": "multi_line_text_field",
  "table.custom_1": "multi_line_text_field",
  "table.custom_2": "multi_line_text_field",
  "table.custom_3": "multi_line_text_field",
  "table.custom_4": "multi_line_text_field",
  "table.custom_5": "multi_line_text_field",
  "table.custom_6": "multi_line_text_field",
  "table.custom_7": "multi_line_text_field",
  "table.custom_8": "multi_line_text_field",
  "table.custom_9": "multi_line_text_field",
  "table.custom_10": "multi_line_text_field",
  "table.custom_11": "multi_line_text_field",
  "table.custom_12": "multi_line_text_field",
  "table.custom_13": "multi_line_text_field",
  "table.custom_14": "multi_line_text_field",
  "table.custom_15": "multi_line_text_field",
  "table.custom_16": "multi_line_text_field",
  "table.custom_17": "multi_line_text_field",
  "table.custom_18": "multi_line_text_field",
  "table.custom_19": "multi_line_text_field",
  "table.custom_20": "multi_line_text_field",
  "table.custom_21": "multi_line_text_field",
  "table.custom_22": "multi_line_text_field",
  "table.custom_23": "multi_line_text_field",
  "table.custom_24": "multi_line_text_field",
  "table.custom_25": "multi_line_text_field",
  "table.custom_26": "multi_line_text_field",
  "table.custom_27": "multi_line_text_field",
  "table.custom_28": "multi_line_text_field",
  "table.custom_29": "multi_line_text_field",
  "table.custom_30": "multi_line_text_field",
  "table.custom_31": "multi_line_text_field",
  "table.custom_32": "multi_line_text_field",
  "table.custom_33": "multi_line_text_field",
  "table.custom_34": "multi_line_text_field",
  "table.custom_35": "multi_line_text_field",
  "table.custom_36": "multi_line_text_field",
  "table.custom_37": "multi_line_text_field",
  "table.custom_38": "multi_line_text_field",
  "table.custom_39": "multi_line_text_field",
  "table.custom_40": "multi_line_text_field",
  // content
  "content.highlight": "rich_text_field",
  "content.specification": "rich_text_field",
  "content.specification_html":"multi_line_text_field",
  "content.application": "rich_text_field",
  "content.features": "rich_text_field",
  //Brand
  "custom.compatibility": "list.single_line_text_field",
};

export const metafieldOptions = {
  "filter.transceiverType": ["Copper Tranceiver (RJ45)", "Fiber Optic Tranceiver", "DAC Cable (Direct Attach Copper)", "AOC Cable (Active Optical Cable)"],
  "filter.fiberMode": ["Single-mode", "OM1", "OM2", "OM3", "OM4", "OM5","Multimode"],
  "filter.connectorType": ["LC", "SC", "ST", "FC", "MTP®", "MPO", "MMC", "RJ45", "CS", "SN", "LC Uniboot","MDC"],
  "filter.polishType": ["UPC ↔ UPC", "APC ↔ APC", "APC ↔ UPC","APC","UPC"],
  "filter.transmissionMode": ["Duplex", "Simplex"],
  "filter.insertionLossGrade": ["0.1dB","0.15dB","0.2dB","0.3dB","0.35dB","0.75dB"],
  "filter.transmissionDistance": ["AOC ≤100m","Direct Attach (DAC)  (≤7m)", "≤ 1000m", "1 ~ 10km", "11 ~ 40km", "41 ~ 80 km", "81 ~ 100km", "≥ 101km", "≤ 100m", "101m ~ 1000m", "AOC ≤10m", "AOC 11–30m", "AOC 31–100m"],
  "filter.data_rate_gbps": ["1G SFP", "2.5G SFP", "4G SFP", "10G SFP+", "25G SFP28", "40G QSFP+", "100G QSFP28", "200G QSFP56", "400G QSFP-DD", "400G OSFP","400G QSFP112", "50G（QSFP28 / SFP56）", "56G QSFP+", "800G QSFP", "800G QSFP-DD", "800G OSFP"],
  "filter.branchType": ["Jumpers", "Harnesses", "Trunks"],
  "filter.fiberCount": ["2 fibers","4 fibers","8 fibers", "12 fibers", "16 fibers", "24 fibers", "48 fibers","64 fibers", "72 fibers", "96 fibers", "144 fibers"],
  "filter.connectorGender": ["Male (Pinned)", "Female (Non-Pinned)"],
  "filter.connectorColor": ["Magenta", "Aqua", "Beige", "Green", "Blue", "Metal", "Yellow", "Lemon Yellow", "Lime Green"],
  "filter.jacketColor": ["Aqua", "Magenta", "Lime Green", "Yellow", "Black", "White","Orange"],
  "filter.jacket": ["OFNR", "LSZH", "OFNP", "UV Resistant", "UV Resistant Armored", "Armored"],
  "filter.wavelength_filter": ["850 nm", "1310 nm", "1550 nm", "Copper"],
  "filter.polarity": ["Type A", "Type B", "Type C"],
  "custom.compatibility": ["Cisco", "Intel", "NVIDIA", "Netgear", "HP", "Dell", "Juniper", "Arista", "Mellanox", "Broadcom","Generic", "Others (custom compatibility)",],
  "filter.bodyType": ["Switchable no Push Pull","Switchable with Push Pull","ACON Easy-Pull"],
  "filter.gender": ["Pinned (Male) - Pinned (Male)","Pinned (Male) - Non-pinned (Female)","Non-pinned (Female) - Non-pinned (Female)"],
  "filter.connector_a": ["LC / UPC", "SC / UPC", "ST / UPC", "FC / UPC", "LC / APC", "SC / APC", "ST / APC", "FC / APC", "Same A/B ends"],
  "filter.connector_b": ["LC / UPC", "SC / UPC", "ST / UPC", "FC / UPC", "LC / APC", "SC / APC", "ST / APC", "FC / APC"],
};
